name: Run Python Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python scripts
      run: |
        mkdir -p logs
        for script in tasks/*.py; do
          python "$script" >> logs/output.log 2>&1 || exit 1
        done

    - name: Commit and push logs
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add logs/output.log
        git commit -m 'Add logs from GitHub Actions workflow'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}